### ISSUE TITLE
progress bar please

### ISSUE THREAD

**Issue by bendichter** [dandi/metadata-dumps#4]
It's taking a long time to run `dandi ls` on the Tolias dataset. I know that's pynwb's fault but still it would be nice to at least have a progress bar. I am partial to tqdm.

**Comment by yarikoptic** [comment]
since ATM output of `ls -f json` is also dumped to stdout not sure if there would be an easy and reliable way to provide progress bar without interfering with the output.  Having said that -- it might be feasible if there would be a dedicated option (`-o, --output`) to specify an output filename instead of stdout.

**Comment by bendichter** [comment]
sounds like a plan

**Comment by yarikoptic** [comment]
this repo/scripts are no longer used, closing for clearing up the space of issues
